apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.webapp.image }}
        ports:
        - containerPort: {{ .Values.webapp.port }}
        env:
        - name: DB_HOST
          value: {{ .Release.Name }}-postgresql
        - name: DB_NAME
          value: {{ .Values.postgresql.auth.database }}
        - name: DB_USER
          value: {{ .Values.postgresql.auth.username }}
        - name: DB_PASSWORD
          value: {{ .Values.postgresql.auth.password }} 